In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import numpy as np
import pandas as pd
import cv2

In [3]:
from slide_segmentation.ocr.blockSkipSegmentator import BlockSkipSegmentator

C:\Users\alistar\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\alistar\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=T

In [4]:
img_files = list(Path("C:\\Users\\alistar\\Desktop\\ds\\video_segmentation\\data\\tmp\\acm_traffic_light").glob("*.jpg"))
chuck_size = 10

In [5]:
img_files = sorted(img_files, key=lambda file: int(file.name.split(".")[0])) #skip the first img

In [6]:
img_files_blocks = np.array_split(img_files, len(img_files)//chuck_size)

In [7]:
#video_name = img_file_dir.split("\\")[-1]
img_file_dict = {int(file.name.split(".")[0]): cv2.imread(str(file), cv2.IMREAD_GRAYSCALE) 
                 for file in img_files}

In [8]:
from slide_segmentation.ocr.config import *
ocr = init_ocr()

C:\Users\alistar\Anaconda3\lib\site-packages\skimage\morphology\_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
C:\Users\alistar\Anaconda3\lib\site-packages\skimage\morphology\_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)


Namespace(cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\alistar/.paddleocr/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:/Users/alistar/Desktop/ds/PaddleOCR-release-2.1/ch_ppocr_server_v2.0_det_infer/', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='C:/Users/alistar/Desktop/ds/PaddleOCR-release-2.1/ppocr/utils/en_dict.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:/Users/alistar/Desktop/ds/PaddleOCR-release-2.1/models/en_number_mobile_v2.0_rec_infer/', use_angle_cls=False, use_dilation=False, use_gpu=True, use_pdserving=False, use_space_char=

In [9]:
segmentator = BlockSkipSegmentator(chunk_size=10, img_file_dict=img_file_dict, ocr_model=ocr, clf_model=new_slide_clf)

In [10]:
np.array_split(list(img_file_dict), len(img_file_dict)//10)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]),
 array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]),
 array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]),
 array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53]),
 array([54, 55, 56, 57, 58, 59, 60, 61, 62, 63]),
 array([64, 65, 66, 67, 68, 69, 70, 71, 72, 73]),
 array([74, 75, 76, 77, 78, 79, 80, 81, 82, 83]),
 array([84, 85, 86, 87, 88, 89, 90, 91, 92, 93]),
 array([ 94,  95,  96,  97,  98,  99, 100, 101, 102, 103]),
 array([104, 105, 106, 107, 108, 109, 110, 111, 112, 113]),
 array([114, 115, 116, 117, 118, 119, 120, 121, 122, 123]),
 array([124, 125, 126, 127, 128, 129, 130, 131, 132, 133]),
 array([134, 135, 136, 137, 138, 139, 140, 141, 142, 143]),
 array([144, 145, 146, 147, 148, 149, 150, 151, 152, 153]),
 array([154, 155, 156, 157, 158, 159, 160, 161, 162, 163]),
 array([164, 165, 166, 167, 168, 169, 170, 171, 172, 173]),
 array([174, 175, 176, 177, 178, 179, 180, 181, 182, 1

In [11]:
segmentation_result = segmentator.get_slide_breakpoints()

INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:16:30] root INFO: dt_boxes num : 18, elapse : 0.4098703861236572
[2022/06/11 22:16:31] root INFO: rec_res num  : 18, elapse : 0.40506601333618164
[2022/06/11 22:16:31] root INFO: dt_boxes num : 16, elapse : 0.337054967880249
[2022/06/11 22:16:31] root INFO: rec_res num  : 16, elapse : 0.35062527656555176


INFO:skip_segmentation:0
INFO:skip_segmentation:False
INFO:skip_segmentation:0 is False breakpoint
INFO:skip_segmentation:block index range: (0, 10)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:16:32] root INFO: dt_boxes num : 15, elapse : 0.3317103385925293
[2022/06/11 22:16:32] root INFO: rec_res num  : 15, elapse : 0.30382394790649414
[2022/06/11 22:16:33] root INFO: dt_boxes num : 17, elapse : 0.3330390453338623
[2022/06/11 22:16:33] root INFO: rec_res num  : 17, elapse : 0.40250086784362793


INFO:skip_segmentation:11
INFO:skip_segmentation:False
INFO:skip_segmentation:11 is False breakpoint
INFO:skip_segmentation:block index range: (11, 21)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:16:33] root INFO: dt_boxes num : 15, elapse : 0.32858800888061523
[2022/06/11 22:16:34] root INFO: rec_res num  : 15, elapse : 0.32247114181518555
[2022/06/11 22:16:34] root INFO: dt_boxes num : 32, elapse : 0.35636186599731445
[2022/06/11 22:16:35] root INFO: rec_res num  : 32, elapse : 0.9970958232879639


INFO:skip_segmentation:22
INFO:skip_segmentation:False
INFO:skip_segmentation:22 is False breakpoint
INFO:skip_segmentation:block index range: (22, 32)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/11 22:16:35] root INFO: dt_boxes num : 16, elapse : 0.32918858528137207
[2022/06/11 22:16:36] root INFO: rec_res num  : 16, elapse : 0.3483295440673828
[2022/06/11 22:16:36] root INFO: dt_boxes num : 16, elapse : 0.3635599613189697
[2022/06/11 22:16:36] root INFO: rec_res num  : 16, elapse : 0.32671666145324707
[2022/06/11 22:16:37] root INFO: dt_boxes num : 30, elapse : 0.328934907913208
[2022/06/11 22:16:38] root INFO: rec_res num  : 30, elapse : 1.0698792934417725
[2022/06/11 22:16:38] root INFO: dt_boxes num : 29, elapse : 0.36899805068969727
[2022/06/11 22:16:39] root INFO: rec_res num  : 29, elapse : 1.015307903289795
[2022/06/11 22:16:40] root INFO: dt_boxes num : 29, elapse : 0.33759450912475586
[2022/06/11 22:16:41] root INFO: rec_res num  : 29, elapse : 0.9963240623474121
[2022/06/11 22:16:41] root INFO: dt_boxes num : 29, elapse : 0.33492183685302734
[2022/06/11 22:16:42] root INFO: rec_res num  : 29, elapse : 1.0128772258758545
[2022/06/11 22:16:42] root INFO: dt_b

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.24390243902439024, 'jaccard': 0.9322033898305084, 'letter_dissim': 0.7203125, 'word_dis': 0.6666666666666666, 'frame_token_ct': 640, 'index': 25, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:16:47] root INFO: dt_boxes num : 32, elapse : 0.41126561164855957
[2022/06/11 22:16:48] root INFO: rec_res num  : 32, elapse : 1.1576697826385498
[2022/06/11 22:16:48] root INFO: dt_boxes num : 34, elapse : 0.4038548469543457
[2022/06/11 22:16:50] root INFO: rec_res num  : 34, elapse : 1.184187889099121


INFO:skip_segmentation:33
INFO:skip_segmentation:False
INFO:skip_segmentation:33 is False breakpoint
INFO:skip_segmentation:block index range: (33, 43)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:16:50] root INFO: dt_boxes num : 33, elapse : 0.3492546081542969
[2022/06/11 22:16:51] root INFO: rec_res num  : 33, elapse : 1.030153751373291
[2022/06/11 22:16:51] root INFO: dt_boxes num : 32, elapse : 0.343686580657959
[2022/06/11 22:16:52] root INFO: rec_res num  : 32, elapse : 0.9761979579925537


INFO:skip_segmentation:44
INFO:skip_segmentation:False
INFO:skip_segmentation:44 is False breakpoint
INFO:skip_segmentation:block index range: (44, 53)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:16:53] root INFO: dt_boxes num : 32, elapse : 0.32661867141723633
[2022/06/11 22:16:54] root INFO: rec_res num  : 32, elapse : 1.0251920223236084
[2022/06/11 22:16:54] root INFO: dt_boxes num : 31, elapse : 0.324535608291626
[2022/06/11 22:16:55] root INFO: rec_res num  : 31, elapse : 1.0539846420288086


INFO:skip_segmentation:54
INFO:skip_segmentation:False
INFO:skip_segmentation:54 is False breakpoint
INFO:skip_segmentation:block index range: (54, 63)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:16:56] root INFO: dt_boxes num : 31, elapse : 0.3389260768890381
[2022/06/11 22:16:57] root INFO: rec_res num  : 31, elapse : 1.0196113586425781
[2022/06/11 22:16:57] root INFO: dt_boxes num : 35, elapse : 0.3339221477508545
[2022/06/11 22:16:58] root INFO: rec_res num  : 35, elapse : 1.0590136051177979


INFO:skip_segmentation:64
INFO:skip_segmentation:False
INFO:skip_segmentation:64 is False breakpoint
INFO:skip_segmentation:block index range: (64, 73)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:16:58] root INFO: dt_boxes num : 35, elapse : 0.39948248863220215
[2022/06/11 22:17:00] root INFO: rec_res num  : 35, elapse : 1.0980322360992432
[2022/06/11 22:17:00] root INFO: dt_boxes num : 14, elapse : 0.34613752365112305
[2022/06/11 22:17:00] root INFO: rec_res num  : 14, elapse : 0.23812079429626465


INFO:skip_segmentation:74
INFO:skip_segmentation:False
INFO:skip_segmentation:74 is False breakpoint
INFO:skip_segmentation:block index range: (74, 83)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/11 22:17:01] root INFO: dt_boxes num : 31, elapse : 0.34189319610595703
[2022/06/11 22:17:02] root INFO: rec_res num  : 31, elapse : 1.0033071041107178
[2022/06/11 22:17:02] root INFO: dt_boxes num : 31, elapse : 0.32900261878967285
[2022/06/11 22:17:03] root INFO: rec_res num  : 31, elapse : 1.0225677490234375
[2022/06/11 22:17:03] root INFO: dt_boxes num : 30, elapse : 0.32412266731262207
[2022/06/11 22:17:04] root INFO: rec_res num  : 30, elapse : 1.0002458095550537
[2022/06/11 22:17:05] root INFO: dt_boxes num : 32, elapse : 0.330167293548584
[2022/06/11 22:17:06] root INFO: rec_res num  : 32, elapse : 1.034153699874878
[2022/06/11 22:17:06] root INFO: dt_boxes num : 31, elapse : 0.33713769912719727
[2022/06/11 22:17:07] root INFO: rec_res num  : 31, elapse : 1.113865852355957
[2022/06/11 22:17:07] root INFO: dt_boxes num : 33, elapse : 0.3231956958770752
[2022/06/11 22:17:09] root INFO: rec_res num  : 33, elapse : 1.0562245845794678
[2022/06/11 22:17:09] root INFO: dt_box

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.46511627906976744, 'jaccard': 0.9622641509433962, 'letter_dissim': 0.8907185628742516, 'word_dis': 0.8507462686567164, 'frame_token_ct': 73, 'index': 81, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:10] root INFO: dt_boxes num : 18, elapse : 0.3218803405761719
[2022/06/11 22:17:10] root INFO: rec_res num  : 18, elapse : 0.37899255752563477
[2022/06/11 22:17:11] root INFO: dt_boxes num : 15, elapse : 0.3403499126434326
[2022/06/11 22:17:11] root INFO: rec_res num  : 15, elapse : 0.2237863540649414


INFO:skip_segmentation:84
INFO:skip_segmentation:False
INFO:skip_segmentation:84 is False breakpoint
INFO:skip_segmentation:block index range: (84, 93)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:11] root INFO: dt_boxes num : 16, elapse : 0.34668850898742676
[2022/06/11 22:17:12] root INFO: rec_res num  : 16, elapse : 0.28402066230773926
[2022/06/11 22:17:12] root INFO: dt_boxes num : 15, elapse : 0.3177347183227539
[2022/06/11 22:17:12] root INFO: rec_res num  : 15, elapse : 0.24725675582885742


INFO:skip_segmentation:94
INFO:skip_segmentation:False
INFO:skip_segmentation:94 is False breakpoint
INFO:skip_segmentation:block index range: (94, 103)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:13] root INFO: dt_boxes num : 19, elapse : 0.34830188751220703
[2022/06/11 22:17:13] root INFO: rec_res num  : 19, elapse : 0.3955848217010498
[2022/06/11 22:17:13] root INFO: dt_boxes num : 19, elapse : 0.32550668716430664
[2022/06/11 22:17:14] root INFO: rec_res num  : 19, elapse : 0.44345593452453613


INFO:skip_segmentation:104
INFO:skip_segmentation:False
INFO:skip_segmentation:104 is False breakpoint
INFO:skip_segmentation:block index range: (104, 113)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:14] root INFO: dt_boxes num : 17, elapse : 0.38762760162353516
[2022/06/11 22:17:15] root INFO: rec_res num  : 17, elapse : 0.3718886375427246
[2022/06/11 22:17:15] root INFO: dt_boxes num : 16, elapse : 0.35622143745422363
[2022/06/11 22:17:15] root INFO: rec_res num  : 16, elapse : 0.3112308979034424


INFO:skip_segmentation:114
INFO:skip_segmentation:False
INFO:skip_segmentation:114 is False breakpoint
INFO:skip_segmentation:block index range: (114, 123)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:16] root INFO: dt_boxes num : 18, elapse : 0.34517335891723633
[2022/06/11 22:17:16] root INFO: rec_res num  : 18, elapse : 0.37743234634399414
[2022/06/11 22:17:16] root INFO: dt_boxes num : 13, elapse : 0.3376452922821045
[2022/06/11 22:17:17] root INFO: rec_res num  : 13, elapse : 0.20142149925231934


INFO:skip_segmentation:124
INFO:skip_segmentation:False
INFO:skip_segmentation:124 is False breakpoint
INFO:skip_segmentation:block index range: (124, 133)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:17] root INFO: dt_boxes num : 17, elapse : 0.3518235683441162
[2022/06/11 22:17:17] root INFO: rec_res num  : 17, elapse : 0.33924341201782227
[2022/06/11 22:17:18] root INFO: dt_boxes num : 18, elapse : 0.3231010437011719
[2022/06/11 22:17:18] root INFO: rec_res num  : 18, elapse : 0.41291236877441406


INFO:skip_segmentation:134
INFO:skip_segmentation:False
INFO:skip_segmentation:134 is False breakpoint
INFO:skip_segmentation:block index range: (134, 143)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:19] root INFO: dt_boxes num : 15, elapse : 0.33785462379455566
[2022/06/11 22:17:19] root INFO: rec_res num  : 15, elapse : 0.39856410026550293
[2022/06/11 22:17:19] root INFO: dt_boxes num : 15, elapse : 0.38315677642822266
[2022/06/11 22:17:20] root INFO: rec_res num  : 15, elapse : 0.3959043025970459


INFO:skip_segmentation:144
INFO:skip_segmentation:True
INFO:skip_segmentation:144 is True breakpoint
INFO:skip_segmentation:block index range: (144, 153)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:20] root INFO: dt_boxes num : 13, elapse : 0.33507442474365234
[2022/06/11 22:17:21] root INFO: rec_res num  : 13, elapse : 0.45853400230407715
[2022/06/11 22:17:21] root INFO: dt_boxes num : 4, elapse : 0.34891557693481445
[2022/06/11 22:17:21] root INFO: rec_res num  : 4, elapse : 0.055315494537353516


INFO:skip_segmentation:154
INFO:skip_segmentation:False
INFO:skip_segmentation:154 is False breakpoint
INFO:skip_segmentation:block index range: (154, 163)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/11 22:17:21] root INFO: dt_boxes num : 10, elapse : 0.3170437812805176
[2022/06/11 22:17:22] root INFO: rec_res num  : 10, elapse : 0.1622769832611084
[2022/06/11 22:17:22] root INFO: dt_boxes num : 10, elapse : 0.34168004989624023
[2022/06/11 22:17:22] root INFO: rec_res num  : 10, elapse : 0.15470051765441895
[2022/06/11 22:17:22] root INFO: dt_boxes num : 11, elapse : 0.3173644542694092
[2022/06/11 22:17:23] root INFO: rec_res num  : 11, elapse : 0.18495607376098633
[2022/06/11 22:17:23] root INFO: dt_boxes num : 9, elapse : 0.32531046867370605
[2022/06/11 22:17:23] root INFO: rec_res num  : 9, elapse : 0.14880919456481934
[2022/06/11 22:17:23] root INFO: dt_boxes num : 10, elapse : 0.3250904083251953
[2022/06/11 22:17:24] root INFO: rec_res num  : 10, elapse : 0.15330958366394043
[2022/06/11 22:17:24] root INFO: dt_boxes num : 10, elapse : 0.3481314182281494
[2022/06/11 22:17:24] root INFO: rec_res num  : 10, elapse : 0.1518244743347168
[2022/06/11 22:17:24] root INFO: dt_

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.3448275862068966, 'jaccard': 0.8846153846153846, 'letter_dissim': 0.7980295566502463, 'word_dis': 0.7586206896551724, 'frame_token_ct': 41, 'index': 155, 'new_slide_prediction': True}, {'jaccard_letter': 0.5909090909090909, 'jaccard': 1.0, 'letter_dissim': 0.4888888888888889, 'word_dis': 0.2857142857142857, 'frame_token_ct': 45, 'index': 163, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:25] root INFO: dt_boxes num : 4, elapse : 0.3326385021209717
[2022/06/11 22:17:26] root INFO: rec_res num  : 4, elapse : 0.059194326400756836
[2022/06/11 22:17:26] root INFO: dt_boxes num : 2, elapse : 0.33526134490966797
[2022/06/11 22:17:26] root INFO: rec_res num  : 2, elapse : 0.03558611869812012


INFO:skip_segmentation:164
INFO:skip_segmentation:False
INFO:skip_segmentation:164 is False breakpoint
INFO:skip_segmentation:block index range: (164, 173)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/11 22:17:26] root INFO: dt_boxes num : 4, elapse : 0.329866886138916
[2022/06/11 22:17:26] root INFO: rec_res num  : 4, elapse : 0.05815529823303223
[2022/06/11 22:17:27] root INFO: dt_boxes num : 4, elapse : 0.3307154178619385
[2022/06/11 22:17:27] root INFO: rec_res num  : 4, elapse : 0.06355476379394531
[2022/06/11 22:17:27] root INFO: dt_boxes num : 4, elapse : 0.36174726486206055
[2022/06/11 22:17:27] root INFO: rec_res num  : 4, elapse : 0.05852460861206055
[2022/06/11 22:17:28] root INFO: dt_boxes num : 4, elapse : 0.31311583518981934
[2022/06/11 22:17:28] root INFO: rec_res num  : 4, elapse : 0.05451250076293945
[2022/06/11 22:17:28] root INFO: dt_boxes num : 4, elapse : 0.32118916511535645
[2022/06/11 22:17:28] root INFO: rec_res num  : 4, elapse : 0.05565524101257324
[2022/06/11 22:17:28] root INFO: dt_boxes num : 4, elapse : 0.34325432777404785
[2022/06/11 22:17:28] root INFO: rec_res num  : 4, elapse : 0.06172609329223633
[2022/06/11 22:17:29] root INFO: dt_boxes n

INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:30] root INFO: dt_boxes num : 2, elapse : 0.34327173233032227
[2022/06/11 22:17:30] root INFO: rec_res num  : 2, elapse : 0.02892279624938965
[2022/06/11 22:17:30] root INFO: dt_boxes num : 2, elapse : 0.32707715034484863
[2022/06/11 22:17:30] root INFO: rec_res num  : 2, elapse : 0.028813838958740234


INFO:skip_segmentation:174
INFO:skip_segmentation:False
INFO:skip_segmentation:174 is False breakpoint
INFO:skip_segmentation:block index range: (174, 183)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:30] root INFO: dt_boxes num : 2, elapse : 0.3373677730560303
[2022/06/11 22:17:30] root INFO: rec_res num  : 2, elapse : 0.029955625534057617
[2022/06/11 22:17:31] root INFO: dt_boxes num : 6, elapse : 0.33593130111694336
[2022/06/11 22:17:31] root INFO: rec_res num  : 6, elapse : 0.6353738307952881


INFO:skip_segmentation:184
INFO:skip_segmentation:False
INFO:skip_segmentation:184 is False breakpoint
INFO:skip_segmentation:block index range: (184, 193)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/11 22:17:32] root INFO: dt_boxes num : 2, elapse : 0.34134435653686523
[2022/06/11 22:17:32] root INFO: rec_res num  : 2, elapse : 0.025047779083251953
[2022/06/11 22:17:32] root INFO: dt_boxes num : 2, elapse : 0.3405647277832031
[2022/06/11 22:17:32] root INFO: rec_res num  : 2, elapse : 0.03717374801635742
[2022/06/11 22:17:33] root INFO: dt_boxes num : 2, elapse : 0.3552286624908447
[2022/06/11 22:17:33] root INFO: rec_res num  : 2, elapse : 0.027008771896362305
[2022/06/11 22:17:33] root INFO: dt_boxes num : 7, elapse : 0.34694433212280273
[2022/06/11 22:17:34] root INFO: rec_res num  : 7, elapse : 0.5019752979278564
[2022/06/11 22:17:34] root INFO: dt_boxes num : 8, elapse : 0.3510773181915283
[2022/06/11 22:17:35] root INFO: rec_res num  : 8, elapse : 0.5916588306427002
[2022/06/11 22:17:35] root INFO: dt_boxes num : 8, elapse : 0.3260030746459961
[2022/06/11 22:17:35] root INFO: rec_res num  : 8, elapse : 0.6142303943634033
[2022/06/11 22:17:36] root INFO: dt_boxes num

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.925, 'jaccard': 1.0, 'letter_dissim': 0.9829059829059829, 'word_dis': 0.9523809523809523, 'frame_token_ct': 234, 'index': 188, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:38] root INFO: dt_boxes num : 6, elapse : 0.3336141109466553
[2022/06/11 22:17:38] root INFO: rec_res num  : 6, elapse : 0.581493616104126
[2022/06/11 22:17:39] root INFO: dt_boxes num : 28, elapse : 0.4218165874481201
[2022/06/11 22:17:40] root INFO: rec_res num  : 28, elapse : 1.2236034870147705


INFO:skip_segmentation:194
INFO:skip_segmentation:False
INFO:skip_segmentation:194 is False breakpoint
INFO:skip_segmentation:block index range: (194, 203)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/11 22:17:40] root INFO: dt_boxes num : 6, elapse : 0.4005296230316162
[2022/06/11 22:17:41] root INFO: rec_res num  : 6, elapse : 0.6150836944580078
[2022/06/11 22:17:41] root INFO: dt_boxes num : 6, elapse : 0.3842897415161133
[2022/06/11 22:17:42] root INFO: rec_res num  : 6, elapse : 0.641258716583252
[2022/06/11 22:17:42] root INFO: dt_boxes num : 6, elapse : 0.3462698459625244
[2022/06/11 22:17:43] root INFO: rec_res num  : 6, elapse : 0.5940151214599609
[2022/06/11 22:17:43] root INFO: dt_boxes num : 6, elapse : 0.356325626373291
[2022/06/11 22:17:44] root INFO: rec_res num  : 6, elapse : 0.5638442039489746
[2022/06/11 22:17:44] root INFO: dt_boxes num : 6, elapse : 0.3437812328338623
[2022/06/11 22:17:45] root INFO: rec_res num  : 6, elapse : 0.5940506458282471
[2022/06/11 22:17:45] root INFO: dt_boxes num : 7, elapse : 0.33597469329833984
[2022/06/11 22:17:46] root INFO: rec_res num  : 7, elapse : 0.48495912551879883
[2022/06/11 22:17:46] root INFO: dt_boxes num : 7, e

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.2564102564102564, 'jaccard': 0.967741935483871, 'letter_dissim': 0.7328358208955223, 'word_dis': 0.7916666666666666, 'frame_token_ct': 670, 'index': 203, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:48] root INFO: dt_boxes num : 27, elapse : 0.3468630313873291
[2022/06/11 22:17:49] root INFO: rec_res num  : 27, elapse : 1.0497946739196777
[2022/06/11 22:17:49] root INFO: dt_boxes num : 26, elapse : 0.3299887180328369
[2022/06/11 22:17:50] root INFO: rec_res num  : 26, elapse : 1.0484051704406738


INFO:skip_segmentation:204
INFO:skip_segmentation:False
INFO:skip_segmentation:204 is False breakpoint
INFO:skip_segmentation:block index range: (204, 213)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:51] root INFO: dt_boxes num : 26, elapse : 0.33066678047180176
[2022/06/11 22:17:52] root INFO: rec_res num  : 26, elapse : 1.088883876800537
[2022/06/11 22:17:52] root INFO: dt_boxes num : 27, elapse : 0.3498270511627197
[2022/06/11 22:17:53] root INFO: rec_res num  : 27, elapse : 1.0224969387054443


INFO:skip_segmentation:214
INFO:skip_segmentation:False
INFO:skip_segmentation:214 is False breakpoint
INFO:skip_segmentation:block index range: (214, 223)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:54] root INFO: dt_boxes num : 27, elapse : 0.3447270393371582
[2022/06/11 22:17:55] root INFO: rec_res num  : 27, elapse : 1.0142066478729248
[2022/06/11 22:17:55] root INFO: dt_boxes num : 28, elapse : 0.351635217666626
[2022/06/11 22:17:56] root INFO: rec_res num  : 28, elapse : 1.037435531616211


INFO:skip_segmentation:224
INFO:skip_segmentation:False
INFO:skip_segmentation:224 is False breakpoint
INFO:skip_segmentation:block index range: (224, 233)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:56] root INFO: dt_boxes num : 28, elapse : 0.3333168029785156
[2022/06/11 22:17:57] root INFO: rec_res num  : 28, elapse : 1.0426528453826904
[2022/06/11 22:17:58] root INFO: dt_boxes num : 28, elapse : 0.34889817237854004
[2022/06/11 22:17:59] root INFO: rec_res num  : 28, elapse : 1.0195226669311523


INFO:skip_segmentation:234
INFO:skip_segmentation:False
INFO:skip_segmentation:234 is False breakpoint
INFO:skip_segmentation:block index range: (234, 243)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:17:59] root INFO: dt_boxes num : 27, elapse : 0.3400423526763916
[2022/06/11 22:18:00] root INFO: rec_res num  : 27, elapse : 0.9934370517730713
[2022/06/11 22:18:01] root INFO: dt_boxes num : 27, elapse : 0.3258507251739502
[2022/06/11 22:18:02] root INFO: rec_res num  : 27, elapse : 1.047684669494629


INFO:skip_segmentation:244
INFO:skip_segmentation:False
INFO:skip_segmentation:244 is False breakpoint
INFO:skip_segmentation:block index range: (244, 253)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:02] root INFO: dt_boxes num : 29, elapse : 0.3277738094329834
[2022/06/11 22:18:03] root INFO: rec_res num  : 29, elapse : 1.054738998413086
[2022/06/11 22:18:03] root INFO: dt_boxes num : 29, elapse : 0.3443112373352051
[2022/06/11 22:18:04] root INFO: rec_res num  : 29, elapse : 1.0686423778533936


INFO:skip_segmentation:254
INFO:skip_segmentation:False
INFO:skip_segmentation:254 is False breakpoint
INFO:skip_segmentation:block index range: (254, 263)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:05] root INFO: dt_boxes num : 28, elapse : 0.3375096321105957
[2022/06/11 22:18:06] root INFO: rec_res num  : 28, elapse : 1.0513732433319092
[2022/06/11 22:18:06] root INFO: dt_boxes num : 25, elapse : 0.325075626373291
[2022/06/11 22:18:07] root INFO: rec_res num  : 25, elapse : 1.0172686576843262


INFO:skip_segmentation:264
INFO:skip_segmentation:False
INFO:skip_segmentation:264 is False breakpoint
INFO:skip_segmentation:block index range: (264, 273)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:08] root INFO: dt_boxes num : 25, elapse : 0.34756946563720703
[2022/06/11 22:18:09] root INFO: rec_res num  : 25, elapse : 1.0392251014709473
[2022/06/11 22:18:09] root INFO: dt_boxes num : 28, elapse : 0.35971808433532715
[2022/06/11 22:18:10] root INFO: rec_res num  : 28, elapse : 0.9993891716003418


INFO:skip_segmentation:274
INFO:skip_segmentation:False
INFO:skip_segmentation:274 is False breakpoint
INFO:skip_segmentation:block index range: (274, 283)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:10] root INFO: dt_boxes num : 25, elapse : 0.34003162384033203
[2022/06/11 22:18:12] root INFO: rec_res num  : 25, elapse : 1.00590181350708
[2022/06/11 22:18:12] root INFO: dt_boxes num : 26, elapse : 0.3376119136810303
[2022/06/11 22:18:13] root INFO: rec_res num  : 26, elapse : 1.0796072483062744


INFO:skip_segmentation:284
INFO:skip_segmentation:False
INFO:skip_segmentation:284 is False breakpoint
INFO:skip_segmentation:block index range: (284, 293)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:13] root INFO: dt_boxes num : 26, elapse : 0.34104418754577637
[2022/06/11 22:18:14] root INFO: rec_res num  : 26, elapse : 1.094019889831543
[2022/06/11 22:18:15] root INFO: dt_boxes num : 26, elapse : 0.3443882465362549
[2022/06/11 22:18:16] root INFO: rec_res num  : 26, elapse : 1.0458998680114746


INFO:skip_segmentation:294
INFO:skip_segmentation:False
INFO:skip_segmentation:294 is False breakpoint
INFO:skip_segmentation:block index range: (294, 303)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:16] root INFO: dt_boxes num : 27, elapse : 0.33229565620422363
[2022/06/11 22:18:17] root INFO: rec_res num  : 27, elapse : 0.9801955223083496
[2022/06/11 22:18:18] root INFO: dt_boxes num : 25, elapse : 0.3257324695587158
[2022/06/11 22:18:19] root INFO: rec_res num  : 25, elapse : 1.0066087245941162


INFO:skip_segmentation:304
INFO:skip_segmentation:False
INFO:skip_segmentation:304 is False breakpoint
INFO:skip_segmentation:block index range: (304, 313)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:19] root INFO: dt_boxes num : 26, elapse : 0.34821391105651855
[2022/06/11 22:18:20] root INFO: rec_res num  : 26, elapse : 1.0837976932525635
[2022/06/11 22:18:20] root INFO: dt_boxes num : 27, elapse : 0.35973119735717773
[2022/06/11 22:18:21] root INFO: rec_res num  : 27, elapse : 0.9994745254516602


INFO:skip_segmentation:314
INFO:skip_segmentation:False
INFO:skip_segmentation:314 is False breakpoint
INFO:skip_segmentation:block index range: (314, 323)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:22] root INFO: dt_boxes num : 7, elapse : 0.32610106468200684
[2022/06/11 22:18:22] root INFO: rec_res num  : 7, elapse : 0.2568817138671875
[2022/06/11 22:18:22] root INFO: dt_boxes num : 15, elapse : 0.3399384021759033
[2022/06/11 22:18:23] root INFO: rec_res num  : 15, elapse : 1.065237283706665


INFO:skip_segmentation:324
INFO:skip_segmentation:True
INFO:skip_segmentation:324 is True breakpoint
INFO:skip_segmentation:block index range: (324, 333)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/11 22:18:24] root INFO: dt_boxes num : 6, elapse : 0.3322122097015381
[2022/06/11 22:18:24] root INFO: rec_res num  : 6, elapse : 0.46438050270080566
[2022/06/11 22:18:25] root INFO: dt_boxes num : 6, elapse : 0.3382103443145752
[2022/06/11 22:18:25] root INFO: rec_res num  : 6, elapse : 0.4766879081726074
[2022/06/11 22:18:26] root INFO: dt_boxes num : 7, elapse : 0.3377056121826172
[2022/06/11 22:18:26] root INFO: rec_res num  : 7, elapse : 0.24733734130859375
[2022/06/11 22:18:26] root INFO: dt_boxes num : 6, elapse : 0.35781025886535645
[2022/06/11 22:18:27] root INFO: rec_res num  : 6, elapse : 0.4729015827178955
[2022/06/11 22:18:27] root INFO: dt_boxes num : 7, elapse : 0.3329136371612549
[2022/06/11 22:18:27] root INFO: rec_res num  : 7, elapse : 0.2479262351989746
[2022/06/11 22:18:28] root INFO: dt_boxes num : 8, elapse : 0.32769203186035156
[2022/06/11 22:18:28] root INFO: rec_res num  : 8, elapse : 0.3317530155181885
[2022/06/11 22:18:28] root INFO: dt_boxes num : 

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.38235294117647056, 'jaccard': 0.9, 'letter_dissim': 0.8088467614533965, 'word_dis': 0.8048780487804879, 'frame_token_ct': 633, 'index': 333, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:30] root INFO: dt_boxes num : 15, elapse : 0.3942275047302246
[2022/06/11 22:18:31] root INFO: rec_res num  : 15, elapse : 1.2246980667114258
[2022/06/11 22:18:31] root INFO: dt_boxes num : 16, elapse : 0.3726997375488281
[2022/06/11 22:18:33] root INFO: rec_res num  : 16, elapse : 1.1058077812194824


INFO:skip_segmentation:334
INFO:skip_segmentation:False
INFO:skip_segmentation:334 is False breakpoint
INFO:skip_segmentation:block index range: (334, 343)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:33] root INFO: dt_boxes num : 16, elapse : 0.3585331439971924
[2022/06/11 22:18:34] root INFO: rec_res num  : 16, elapse : 1.0364155769348145
[2022/06/11 22:18:34] root INFO: dt_boxes num : 17, elapse : 0.33323121070861816
[2022/06/11 22:18:35] root INFO: rec_res num  : 17, elapse : 1.1118288040161133


INFO:skip_segmentation:344
INFO:skip_segmentation:False
INFO:skip_segmentation:344 is False breakpoint
INFO:skip_segmentation:block index range: (344, 353)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:36] root INFO: dt_boxes num : 17, elapse : 0.3326094150543213
[2022/06/11 22:18:37] root INFO: rec_res num  : 17, elapse : 1.078413486480713
[2022/06/11 22:18:37] root INFO: dt_boxes num : 16, elapse : 0.33477330207824707
[2022/06/11 22:18:38] root INFO: rec_res num  : 16, elapse : 1.0236945152282715


INFO:skip_segmentation:354
INFO:skip_segmentation:False
INFO:skip_segmentation:354 is False breakpoint
INFO:skip_segmentation:block index range: (354, 363)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:39] root INFO: dt_boxes num : 16, elapse : 0.3237905502319336
[2022/06/11 22:18:40] root INFO: rec_res num  : 16, elapse : 1.0547518730163574
[2022/06/11 22:18:40] root INFO: dt_boxes num : 16, elapse : 0.342862606048584
[2022/06/11 22:18:41] root INFO: rec_res num  : 16, elapse : 1.149083137512207


INFO:skip_segmentation:364
INFO:skip_segmentation:False
INFO:skip_segmentation:364 is False breakpoint
INFO:skip_segmentation:block index range: (364, 373)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:42] root INFO: dt_boxes num : 16, elapse : 0.4271078109741211
[2022/06/11 22:18:43] root INFO: rec_res num  : 16, elapse : 1.1717548370361328
[2022/06/11 22:18:43] root INFO: dt_boxes num : 15, elapse : 0.353008508682251
[2022/06/11 22:18:44] root INFO: rec_res num  : 15, elapse : 0.9954960346221924


INFO:skip_segmentation:374
INFO:skip_segmentation:False
INFO:skip_segmentation:374 is False breakpoint
INFO:skip_segmentation:block index range: (374, 383)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:45] root INFO: dt_boxes num : 14, elapse : 0.3274993896484375
[2022/06/11 22:18:46] root INFO: rec_res num  : 14, elapse : 1.1589572429656982
[2022/06/11 22:18:46] root INFO: dt_boxes num : 14, elapse : 0.3660318851470947
[2022/06/11 22:18:47] root INFO: rec_res num  : 14, elapse : 1.0272655487060547


INFO:skip_segmentation:384
INFO:skip_segmentation:False
INFO:skip_segmentation:384 is False breakpoint
INFO:skip_segmentation:block index range: (384, 393)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:48] root INFO: dt_boxes num : 15, elapse : 0.3330569267272949
[2022/06/11 22:18:49] root INFO: rec_res num  : 15, elapse : 1.0211565494537354
[2022/06/11 22:18:49] root INFO: dt_boxes num : 16, elapse : 0.3331277370452881
[2022/06/11 22:18:50] root INFO: rec_res num  : 16, elapse : 1.06593656539917


INFO:skip_segmentation:394
INFO:skip_segmentation:False
INFO:skip_segmentation:394 is False breakpoint
INFO:skip_segmentation:block index range: (394, 403)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:50] root INFO: dt_boxes num : 16, elapse : 0.3446321487426758
[2022/06/11 22:18:52] root INFO: rec_res num  : 16, elapse : 1.0929608345031738
[2022/06/11 22:18:52] root INFO: dt_boxes num : 15, elapse : 0.3417832851409912
[2022/06/11 22:18:53] root INFO: rec_res num  : 15, elapse : 1.0844662189483643


INFO:skip_segmentation:404
INFO:skip_segmentation:False
INFO:skip_segmentation:404 is False breakpoint
INFO:skip_segmentation:block index range: (404, 413)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:53] root INFO: dt_boxes num : 15, elapse : 0.3198421001434326
[2022/06/11 22:18:55] root INFO: rec_res num  : 15, elapse : 1.2924277782440186
[2022/06/11 22:18:55] root INFO: dt_boxes num : 16, elapse : 0.3737826347351074
[2022/06/11 22:18:56] root INFO: rec_res num  : 16, elapse : 1.0605425834655762


INFO:skip_segmentation:414
INFO:skip_segmentation:False
INFO:skip_segmentation:414 is False breakpoint
INFO:skip_segmentation:block index range: (414, 423)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:18:57] root INFO: dt_boxes num : 17, elapse : 0.569373369216919
[2022/06/11 22:18:58] root INFO: rec_res num  : 17, elapse : 1.1858680248260498
[2022/06/11 22:18:58] root INFO: dt_boxes num : 16, elapse : 0.3373684883117676
[2022/06/11 22:18:59] root INFO: rec_res num  : 16, elapse : 1.0920240879058838


INFO:skip_segmentation:424
INFO:skip_segmentation:False
INFO:skip_segmentation:424 is False breakpoint
INFO:skip_segmentation:block index range: (424, 433)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:00] root INFO: dt_boxes num : 16, elapse : 0.3638639450073242
[2022/06/11 22:19:01] root INFO: rec_res num  : 16, elapse : 1.1849541664123535
[2022/06/11 22:19:01] root INFO: dt_boxes num : 13, elapse : 0.38666844367980957
[2022/06/11 22:19:02] root INFO: rec_res num  : 13, elapse : 0.850731372833252


INFO:skip_segmentation:434
INFO:skip_segmentation:False
INFO:skip_segmentation:434 is False breakpoint
INFO:skip_segmentation:block index range: (434, 443)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/11 22:19:03] root INFO: dt_boxes num : 16, elapse : 0.33402037620544434
[2022/06/11 22:19:04] root INFO: rec_res num  : 16, elapse : 1.052905797958374
[2022/06/11 22:19:04] root INFO: dt_boxes num : 16, elapse : 0.3524298667907715
[2022/06/11 22:19:05] root INFO: rec_res num  : 16, elapse : 1.0812406539916992
[2022/06/11 22:19:06] root INFO: dt_boxes num : 16, elapse : 0.3912358283996582
[2022/06/11 22:19:07] root INFO: rec_res num  : 16, elapse : 1.2154974937438965
[2022/06/11 22:19:07] root INFO: dt_boxes num : 16, elapse : 0.35138511657714844
[2022/06/11 22:19:08] root INFO: rec_res num  : 16, elapse : 1.1167516708374023
[2022/06/11 22:19:09] root INFO: dt_boxes num : 17, elapse : 0.39954519271850586
[2022/06/11 22:19:10] root INFO: rec_res num  : 17, elapse : 1.1280534267425537
[2022/06/11 22:19:10] root INFO: dt_boxes num : 17, elapse : 0.34722042083740234
[2022/06/11 22:19:11] root INFO: rec_res num  : 17, elapse : 1.0857183933258057
[2022/06/11 22:19:12] root INFO: dt_b

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.09090909090909091, 'jaccard': 0.9042553191489362, 'letter_dissim': 0.27230046948356806, 'word_dis': 0.35365853658536583, 'frame_token_ct': 465, 'index': 442, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:14] root INFO: dt_boxes num : 14, elapse : 0.33193349838256836
[2022/06/11 22:19:15] root INFO: rec_res num  : 14, elapse : 0.8813858032226562
[2022/06/11 22:19:16] root INFO: dt_boxes num : 15, elapse : 0.32967305183410645
[2022/06/11 22:19:17] root INFO: rec_res num  : 15, elapse : 1.0183889865875244


INFO:skip_segmentation:444
INFO:skip_segmentation:False
INFO:skip_segmentation:444 is False breakpoint
INFO:skip_segmentation:block index range: (444, 453)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:17] root INFO: dt_boxes num : 13, elapse : 0.33556604385375977
[2022/06/11 22:19:18] root INFO: rec_res num  : 13, elapse : 0.7863254547119141
[2022/06/11 22:19:18] root INFO: dt_boxes num : 16, elapse : 0.32582688331604004
[2022/06/11 22:19:19] root INFO: rec_res num  : 16, elapse : 0.9476583003997803


INFO:skip_segmentation:454
INFO:skip_segmentation:False
INFO:skip_segmentation:454 is False breakpoint
INFO:skip_segmentation:block index range: (454, 463)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:19] root INFO: dt_boxes num : 16, elapse : 0.3447134494781494
[2022/06/11 22:19:20] root INFO: rec_res num  : 16, elapse : 0.9900367259979248
[2022/06/11 22:19:21] root INFO: dt_boxes num : 14, elapse : 0.3617844581604004
[2022/06/11 22:19:22] root INFO: rec_res num  : 14, elapse : 0.9032995700836182


INFO:skip_segmentation:464
INFO:skip_segmentation:False
INFO:skip_segmentation:464 is False breakpoint
INFO:skip_segmentation:block index range: (464, 473)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:22] root INFO: dt_boxes num : 15, elapse : 0.33200955390930176
[2022/06/11 22:19:23] root INFO: rec_res num  : 15, elapse : 1.0538403987884521
[2022/06/11 22:19:24] root INFO: dt_boxes num : 14, elapse : 0.35741686820983887
[2022/06/11 22:19:24] root INFO: rec_res num  : 14, elapse : 0.902756929397583


INFO:skip_segmentation:474
INFO:skip_segmentation:False
INFO:skip_segmentation:474 is False breakpoint
INFO:skip_segmentation:block index range: (474, 483)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:25] root INFO: dt_boxes num : 14, elapse : 0.3548922538757324
[2022/06/11 22:19:26] root INFO: rec_res num  : 14, elapse : 0.8948945999145508
[2022/06/11 22:19:26] root INFO: dt_boxes num : 23, elapse : 0.32675671577453613
[2022/06/11 22:19:27] root INFO: rec_res num  : 23, elapse : 1.2641804218292236


INFO:skip_segmentation:484
INFO:skip_segmentation:False
INFO:skip_segmentation:484 is False breakpoint
INFO:skip_segmentation:block index range: (484, 493)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/11 22:19:28] root INFO: dt_boxes num : 13, elapse : 0.3292546272277832
[2022/06/11 22:19:28] root INFO: rec_res num  : 13, elapse : 0.7906961441040039
[2022/06/11 22:19:29] root INFO: dt_boxes num : 13, elapse : 0.3414483070373535
[2022/06/11 22:19:30] root INFO: rec_res num  : 13, elapse : 0.8182761669158936
[2022/06/11 22:19:30] root INFO: dt_boxes num : 13, elapse : 0.32291412353515625
[2022/06/11 22:19:31] root INFO: rec_res num  : 13, elapse : 0.7974514961242676
[2022/06/11 22:19:31] root INFO: dt_boxes num : 13, elapse : 0.33255529403686523
[2022/06/11 22:19:32] root INFO: rec_res num  : 13, elapse : 0.796623706817627
[2022/06/11 22:19:32] root INFO: dt_boxes num : 13, elapse : 0.3251357078552246
[2022/06/11 22:19:33] root INFO: rec_res num  : 13, elapse : 0.8470308780670166
[2022/06/11 22:19:34] root INFO: dt_boxes num : 15, elapse : 0.3307681083679199
[2022/06/11 22:19:35] root INFO: rec_res num  : 15, elapse : 1.046638011932373
[2022/06/11 22:19:35] root INFO: dt_boxe

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.2, 'jaccard': 0.9285714285714286, 'letter_dissim': 0.30906389301634474, 'word_dis': 0.35365853658536583, 'frame_token_ct': 673, 'index': 493, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:38] root INFO: dt_boxes num : 24, elapse : 0.36706018447875977
[2022/06/11 22:19:39] root INFO: rec_res num  : 24, elapse : 1.4374511241912842
[2022/06/11 22:19:39] root INFO: dt_boxes num : 23, elapse : 0.32968807220458984
[2022/06/11 22:19:41] root INFO: rec_res num  : 23, elapse : 1.4544298648834229


INFO:skip_segmentation:494
INFO:skip_segmentation:False
INFO:skip_segmentation:494 is False breakpoint
INFO:skip_segmentation:block index range: (494, 503)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:41] root INFO: dt_boxes num : 24, elapse : 0.35234761238098145
[2022/06/11 22:19:43] root INFO: rec_res num  : 24, elapse : 1.4001710414886475
[2022/06/11 22:19:43] root INFO: dt_boxes num : 22, elapse : 0.38918161392211914
[2022/06/11 22:19:44] root INFO: rec_res num  : 22, elapse : 1.1913390159606934


INFO:skip_segmentation:504
INFO:skip_segmentation:False
INFO:skip_segmentation:504 is False breakpoint
INFO:skip_segmentation:block index range: (504, 513)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:45] root INFO: dt_boxes num : 23, elapse : 0.33856844902038574
[2022/06/11 22:19:46] root INFO: rec_res num  : 23, elapse : 1.3385956287384033
[2022/06/11 22:19:46] root INFO: dt_boxes num : 26, elapse : 0.3338618278503418
[2022/06/11 22:19:48] root INFO: rec_res num  : 26, elapse : 1.3084344863891602


INFO:skip_segmentation:514
INFO:skip_segmentation:False
INFO:skip_segmentation:514 is False breakpoint
INFO:skip_segmentation:block index range: (514, 523)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:48] root INFO: dt_boxes num : 25, elapse : 0.3311038017272949
[2022/06/11 22:19:49] root INFO: rec_res num  : 25, elapse : 1.2170941829681396
[2022/06/11 22:19:50] root INFO: dt_boxes num : 21, elapse : 0.34203004837036133
[2022/06/11 22:19:51] root INFO: rec_res num  : 21, elapse : 1.3953039646148682


INFO:skip_segmentation:524
INFO:skip_segmentation:False
INFO:skip_segmentation:524 is False breakpoint
INFO:skip_segmentation:block index range: (524, 533)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:51] root INFO: dt_boxes num : 21, elapse : 0.3331184387207031
[2022/06/11 22:19:53] root INFO: rec_res num  : 21, elapse : 1.211261510848999
[2022/06/11 22:19:53] root INFO: dt_boxes num : 24, elapse : 0.32821011543273926
[2022/06/11 22:19:54] root INFO: rec_res num  : 24, elapse : 1.3690330982208252


INFO:skip_segmentation:534
INFO:skip_segmentation:False
INFO:skip_segmentation:534 is False breakpoint
INFO:skip_segmentation:block index range: (534, 543)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:55] root INFO: dt_boxes num : 23, elapse : 0.32194995880126953
[2022/06/11 22:19:56] root INFO: rec_res num  : 23, elapse : 1.436593770980835
[2022/06/11 22:19:56] root INFO: dt_boxes num : 23, elapse : 0.34534287452697754
[2022/06/11 22:19:58] root INFO: rec_res num  : 23, elapse : 1.2765355110168457


INFO:skip_segmentation:544
INFO:skip_segmentation:False
INFO:skip_segmentation:544 is False breakpoint
INFO:skip_segmentation:block index range: (544, 553)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:19:58] root INFO: dt_boxes num : 22, elapse : 0.3600890636444092
[2022/06/11 22:19:59] root INFO: rec_res num  : 22, elapse : 1.3353652954101562
[2022/06/11 22:20:00] root INFO: dt_boxes num : 12, elapse : 0.384291410446167
[2022/06/11 22:20:00] root INFO: rec_res num  : 12, elapse : 0.36159324645996094


INFO:skip_segmentation:554
INFO:skip_segmentation:False
INFO:skip_segmentation:554 is False breakpoint
INFO:skip_segmentation:block index range: (554, 563)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/11 22:20:01] root INFO: dt_boxes num : 21, elapse : 0.32515525817871094
[2022/06/11 22:20:02] root INFO: rec_res num  : 21, elapse : 1.2442905902862549
[2022/06/11 22:20:02] root INFO: dt_boxes num : 22, elapse : 0.3530540466308594
[2022/06/11 22:20:04] root INFO: rec_res num  : 22, elapse : 1.3374454975128174
[2022/06/11 22:20:04] root INFO: dt_boxes num : 23, elapse : 0.3710057735443115
[2022/06/11 22:20:05] root INFO: rec_res num  : 23, elapse : 1.4301989078521729
[2022/06/11 22:20:06] root INFO: dt_boxes num : 24, elapse : 0.3420846462249756
[2022/06/11 22:20:07] root INFO: rec_res num  : 24, elapse : 1.3962647914886475
[2022/06/11 22:20:08] root INFO: dt_boxes num : 13, elapse : 0.3341052532196045
[2022/06/11 22:20:08] root INFO: rec_res num  : 13, elapse : 0.28024959564208984
[2022/06/11 22:20:08] root INFO: dt_boxes num : 13, elapse : 0.3330841064453125
[2022/06/11 22:20:08] root INFO: rec_res num  : 13, elapse : 0.2982025146484375
[2022/06/11 22:20:09] root INFO: dt_bo

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.4888888888888889, 'jaccard': 0.9452054794520548, 'letter_dissim': 0.778236914600551, 'word_dis': 0.7682926829268293, 'frame_token_ct': 161, 'index': 559, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:20:10] root INFO: dt_boxes num : 13, elapse : 0.45378661155700684
[2022/06/11 22:20:11] root INFO: rec_res num  : 13, elapse : 0.36409783363342285
[2022/06/11 22:20:11] root INFO: dt_boxes num : 12, elapse : 0.39594030380249023
[2022/06/11 22:20:12] root INFO: rec_res num  : 12, elapse : 0.40491819381713867


INFO:skip_segmentation:564
INFO:skip_segmentation:False
INFO:skip_segmentation:564 is False breakpoint
INFO:skip_segmentation:block index range: (564, 573)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:20:12] root INFO: dt_boxes num : 12, elapse : 0.39896488189697266
[2022/06/11 22:20:12] root INFO: rec_res num  : 12, elapse : 0.3660855293273926
[2022/06/11 22:20:13] root INFO: dt_boxes num : 12, elapse : 0.4158937931060791
[2022/06/11 22:20:13] root INFO: rec_res num  : 12, elapse : 0.36968326568603516


INFO:skip_segmentation:574
INFO:skip_segmentation:False
INFO:skip_segmentation:574 is False breakpoint
INFO:skip_segmentation:block index range: (574, 583)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:20:14] root INFO: dt_boxes num : 12, elapse : 0.3438413143157959
[2022/06/11 22:20:14] root INFO: rec_res num  : 12, elapse : 0.3710973262786865
[2022/06/11 22:20:14] root INFO: dt_boxes num : 12, elapse : 0.3725311756134033
[2022/06/11 22:20:15] root INFO: rec_res num  : 12, elapse : 0.3663749694824219


INFO:skip_segmentation:584
INFO:skip_segmentation:False
INFO:skip_segmentation:584 is False breakpoint
INFO:skip_segmentation:block index range: (584, 593)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/11 22:20:15] root INFO: dt_boxes num : 12, elapse : 0.34064531326293945
[2022/06/11 22:20:16] root INFO: rec_res num  : 12, elapse : 0.37165045738220215
[2022/06/11 22:20:16] root INFO: dt_boxes num : 13, elapse : 0.34814882278442383
[2022/06/11 22:20:16] root INFO: rec_res num  : 13, elapse : 0.31179189682006836


INFO:skip_segmentation:594
INFO:skip_segmentation:False
INFO:skip_segmentation:594 is False breakpoint
INFO:skip_segmentation:block index range: (594, 603)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []


In [12]:
segmentation_result 

jaccard_letter   jaccard  letter_dissim  word_dis  frame_token_ct  index  \
0         0.243902  0.932203       0.720313  0.666667             640     25   
1         0.465116  0.962264       0.890719  0.850746              73     81   
2         0.371429  0.911765       0.174129  0.200000             201    144   
3         0.344828  0.884615       0.798030  0.758621              41    155   
4         0.590909  1.000000       0.488889  0.285714              45    163   
5         0.925000  1.000000       0.982906  0.952381             234    188   
6         0.256410  0.967742       0.732836  0.791667             670    203   
7         0.405405  0.927273       0.790698  0.723077             135    324   
8         0.382353  0.900000       0.808847  0.804878             633    333   
9         0.090909  0.904255       0.272300  0.353659             465    442   
10        0.200000  0.928571       0.309064  0.353659             673    493   
11        0.488889  0.945205       0.778237  0.768293             161    559   

    new_slide_prediction  
0                   True  
1                   True  
2                   True  
3                   True  
4                   True  
5                   True  
6                   True  
7                   True  
8                   True  
9                   True  
10                  True  
11                  True