In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import numpy as np
import pandas as pd
import cv2

In [3]:
from slide_segmentation.ocr.blockSkipSegmentator import BlockSkipSegmentator

C:\Users\alistar\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\alistar\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=T

In [4]:
img_files = list(Path("C:\\Users\\alistar\\Desktop\\ds\\video_segmentation\\data\\tmp\\acm_traffic_light").glob("*.jpg"))
chuck_size = 10

In [5]:
img_files = sorted(img_files, key=lambda file: int(file.name.split(".")[0])) #skip the first img

In [6]:
img_files_blocks = np.array_split(img_files, len(img_files)//chuck_size)

In [7]:
#video_name = img_file_dir.split("\\")[-1]
img_file_dict = {int(file.name.split(".")[0]): cv2.imread(str(file), cv2.IMREAD_GRAYSCALE) 
                 for file in img_files}

In [8]:
from slide_segmentation.ocr.config import *
ocr = init_ocr()

C:\Users\alistar\Anaconda3\lib\site-packages\skimage\morphology\_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
C:\Users\alistar\Anaconda3\lib\site-packages\skimage\morphology\_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)


Namespace(cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='C:\\Users\\alistar/.paddleocr/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='C:/Users/alistar/Desktop/ds/PaddleOCR-release-2.1/ch_ppocr_server_v2.0_det_infer/', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='C:/Users/alistar/Desktop/ds/PaddleOCR-release-2.1/ppocr/utils/en_dict.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='C:/Users/alistar/Desktop/ds/PaddleOCR-release-2.1/models/en_number_mobile_v2.0_rec_infer/', use_angle_cls=False, use_dilation=False, use_gpu=True, use_pdserving=False, use_space_char=

In [9]:
segmentator = BlockSkipSegmentator(chunk_size=10, img_file_dict=img_file_dict, ocr_model=ocr, clf_model=new_slide_clf)

In [10]:
np.array_split(list(img_file_dict), len(img_file_dict)//10)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]),
 array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]),
 array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]),
 array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53]),
 array([54, 55, 56, 57, 58, 59, 60, 61, 62, 63]),
 array([64, 65, 66, 67, 68, 69, 70, 71, 72, 73]),
 array([74, 75, 76, 77, 78, 79, 80, 81, 82, 83]),
 array([84, 85, 86, 87, 88, 89, 90, 91, 92, 93]),
 array([ 94,  95,  96,  97,  98,  99, 100, 101, 102, 103]),
 array([104, 105, 106, 107, 108, 109, 110, 111, 112, 113]),
 array([114, 115, 116, 117, 118, 119, 120, 121, 122, 123]),
 array([124, 125, 126, 127, 128, 129, 130, 131, 132, 133]),
 array([134, 135, 136, 137, 138, 139, 140, 141, 142, 143]),
 array([144, 145, 146, 147, 148, 149, 150, 151, 152, 153]),
 array([154, 155, 156, 157, 158, 159, 160, 161, 162, 163]),
 array([164, 165, 166, 167, 168, 169, 170, 171, 172, 173]),
 array([174, 175, 176, 177, 178, 179, 180, 181, 182, 1

In [11]:
segmentation_result = segmentator.get_slide_breakpoints(max_block_count=10)

INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/12 16:50:15] root INFO: dt_boxes num : 18, elapse : 0.36813855171203613
[2022/06/12 16:50:16] root INFO: rec_res num  : 18, elapse : 0.4099161624908447
[2022/06/12 16:50:16] root INFO: dt_boxes num : 16, elapse : 0.3332712650299072
[2022/06/12 16:50:16] root INFO: rec_res num  : 16, elapse : 0.3303496837615967


INFO:skip_segmentation:0
INFO:skip_segmentation:False
INFO:skip_segmentation:0 is False breakpoint
INFO:skip_segmentation:block index range: (0, 10)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/12 16:50:17] root INFO: dt_boxes num : 15, elapse : 0.31357479095458984
[2022/06/12 16:50:17] root INFO: rec_res num  : 15, elapse : 0.2963743209838867
[2022/06/12 16:50:17] root INFO: dt_boxes num : 17, elapse : 0.31810951232910156
[2022/06/12 16:50:18] root INFO: rec_res num  : 17, elapse : 0.3841102123260498


INFO:skip_segmentation:11
INFO:skip_segmentation:False
INFO:skip_segmentation:11 is False breakpoint
INFO:skip_segmentation:block index range: (11, 21)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/12 16:50:18] root INFO: dt_boxes num : 15, elapse : 0.32254862785339355
[2022/06/12 16:50:18] root INFO: rec_res num  : 15, elapse : 0.2923295497894287
[2022/06/12 16:50:19] root INFO: dt_boxes num : 32, elapse : 0.3337252140045166
[2022/06/12 16:50:20] root INFO: rec_res num  : 32, elapse : 0.9611427783966064


INFO:skip_segmentation:22
INFO:skip_segmentation:False
INFO:skip_segmentation:22 is False breakpoint
INFO:skip_segmentation:block index range: (22, 32)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/12 16:50:20] root INFO: dt_boxes num : 16, elapse : 0.3170597553253174
[2022/06/12 16:50:21] root INFO: rec_res num  : 16, elapse : 0.3289787769317627
[2022/06/12 16:50:21] root INFO: dt_boxes num : 16, elapse : 0.32979655265808105
[2022/06/12 16:50:21] root INFO: rec_res num  : 16, elapse : 0.33565640449523926
[2022/06/12 16:50:22] root INFO: dt_boxes num : 30, elapse : 0.32546567916870117
[2022/06/12 16:50:23] root INFO: rec_res num  : 30, elapse : 0.9882707595825195
[2022/06/12 16:50:23] root INFO: dt_boxes num : 29, elapse : 0.3637814521789551
[2022/06/12 16:50:24] root INFO: rec_res num  : 29, elapse : 0.9515583515167236
[2022/06/12 16:50:24] root INFO: dt_boxes num : 29, elapse : 0.3345766067504883
[2022/06/12 16:50:25] root INFO: rec_res num  : 29, elapse : 1.0199484825134277
[2022/06/12 16:50:26] root INFO: dt_boxes num : 29, elapse : 0.35004210472106934
[2022/06/12 16:50:27] root INFO: rec_res num  : 29, elapse : 0.9860472679138184
[2022/06/12 16:50:27] root INFO: dt_

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.24390243902439024, 'jaccard': 0.9322033898305084, 'letter_dissim': 0.7203125, 'word_dis': 0.6666666666666666, 'frame_token_ct': 640, 'index': 25, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/12 16:50:31] root INFO: dt_boxes num : 32, elapse : 0.3682987689971924
[2022/06/12 16:50:32] root INFO: rec_res num  : 32, elapse : 0.9867615699768066
[2022/06/12 16:50:32] root INFO: dt_boxes num : 34, elapse : 0.3444645404815674
[2022/06/12 16:50:34] root INFO: rec_res num  : 34, elapse : 1.0820143222808838


INFO:skip_segmentation:33
INFO:skip_segmentation:False
INFO:skip_segmentation:33 is False breakpoint
INFO:skip_segmentation:block index range: (33, 43)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/12 16:50:34] root INFO: dt_boxes num : 33, elapse : 0.326171875
[2022/06/12 16:50:35] root INFO: rec_res num  : 33, elapse : 1.0333890914916992
[2022/06/12 16:50:35] root INFO: dt_boxes num : 32, elapse : 0.3352372646331787
[2022/06/12 16:50:36] root INFO: rec_res num  : 32, elapse : 0.998603343963623


INFO:skip_segmentation:44
INFO:skip_segmentation:False
INFO:skip_segmentation:44 is False breakpoint
INFO:skip_segmentation:block index range: (44, 53)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/12 16:50:37] root INFO: dt_boxes num : 32, elapse : 0.32332658767700195
[2022/06/12 16:50:38] root INFO: rec_res num  : 32, elapse : 0.9883036613464355
[2022/06/12 16:50:38] root INFO: dt_boxes num : 31, elapse : 0.32207679748535156
[2022/06/12 16:50:39] root INFO: rec_res num  : 31, elapse : 1.0114617347717285


INFO:skip_segmentation:54
INFO:skip_segmentation:False
INFO:skip_segmentation:54 is False breakpoint
INFO:skip_segmentation:block index range: (54, 63)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/12 16:50:39] root INFO: dt_boxes num : 31, elapse : 0.3337118625640869
[2022/06/12 16:50:40] root INFO: rec_res num  : 31, elapse : 0.9896409511566162
[2022/06/12 16:50:41] root INFO: dt_boxes num : 35, elapse : 0.3262786865234375
[2022/06/12 16:50:42] root INFO: rec_res num  : 35, elapse : 1.000138521194458


INFO:skip_segmentation:64
INFO:skip_segmentation:False
INFO:skip_segmentation:64 is False breakpoint
INFO:skip_segmentation:block index range: (64, 73)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/12 16:50:42] root INFO: dt_boxes num : 35, elapse : 0.3210420608520508
[2022/06/12 16:50:43] root INFO: rec_res num  : 35, elapse : 1.0336508750915527
[2022/06/12 16:50:44] root INFO: dt_boxes num : 14, elapse : 0.31855249404907227
[2022/06/12 16:50:44] root INFO: rec_res num  : 14, elapse : 0.24231290817260742


INFO:skip_segmentation:74
INFO:skip_segmentation:False
INFO:skip_segmentation:74 is False breakpoint
INFO:skip_segmentation:block index range: (74, 83)
INFO:skip_segmentation:same slide block: False
INFO:skip_segmentation:




[2022/06/12 16:50:44] root INFO: dt_boxes num : 31, elapse : 0.3311641216278076
[2022/06/12 16:50:45] root INFO: rec_res num  : 31, elapse : 0.9715383052825928
[2022/06/12 16:50:45] root INFO: dt_boxes num : 31, elapse : 0.3292887210845947
[2022/06/12 16:50:46] root INFO: rec_res num  : 31, elapse : 0.9667685031890869
[2022/06/12 16:50:47] root INFO: dt_boxes num : 30, elapse : 0.33446812629699707
[2022/06/12 16:50:48] root INFO: rec_res num  : 30, elapse : 0.9908182621002197
[2022/06/12 16:50:48] root INFO: dt_boxes num : 32, elapse : 0.3277764320373535
[2022/06/12 16:50:49] root INFO: rec_res num  : 32, elapse : 1.0492613315582275
[2022/06/12 16:50:50] root INFO: dt_boxes num : 31, elapse : 0.3593595027923584
[2022/06/12 16:50:51] root INFO: rec_res num  : 31, elapse : 0.9983339309692383
[2022/06/12 16:50:51] root INFO: dt_boxes num : 33, elapse : 0.31563782691955566
[2022/06/12 16:50:52] root INFO: rec_res num  : 33, elapse : 1.081364393234253
[2022/06/12 16:50:52] root INFO: dt_box

INFO:skip_segmentation:block_new_slides: [{'jaccard_letter': 0.46511627906976744, 'jaccard': 0.9622641509433962, 'letter_dissim': 0.8907185628742516, 'word_dis': 0.8507462686567164, 'frame_token_ct': 73, 'index': 81, 'new_slide_prediction': True}]
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/12 16:50:53] root INFO: dt_boxes num : 18, elapse : 0.31804561614990234
[2022/06/12 16:50:54] root INFO: rec_res num  : 18, elapse : 0.3818798065185547
[2022/06/12 16:50:54] root INFO: dt_boxes num : 15, elapse : 0.3153727054595947
[2022/06/12 16:50:54] root INFO: rec_res num  : 15, elapse : 0.22899413108825684


INFO:skip_segmentation:84
INFO:skip_segmentation:False
INFO:skip_segmentation:84 is False breakpoint
INFO:skip_segmentation:block index range: (84, 93)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []
INFO:skip_segmentation:#####
INFO:skip_segmentation:looking at new block
INFO:skip_segmentation:#####


[2022/06/12 16:50:55] root INFO: dt_boxes num : 16, elapse : 0.3157222270965576
[2022/06/12 16:50:55] root INFO: rec_res num  : 16, elapse : 0.2650032043457031
[2022/06/12 16:50:55] root INFO: dt_boxes num : 15, elapse : 0.33321070671081543
[2022/06/12 16:50:56] root INFO: rec_res num  : 15, elapse : 0.23883700370788574


INFO:skip_segmentation:94
INFO:skip_segmentation:False
INFO:skip_segmentation:94 is False breakpoint
INFO:skip_segmentation:block index range: (94, 103)
INFO:skip_segmentation:same slide block: True
INFO:skip_segmentation:


INFO:skip_segmentation:block_new_slides: []


In [12]:
segmentation_result 

jaccard_letter   jaccard  letter_dissim  word_dis  frame_token_ct  index  \
0        0.243902  0.932203       0.720313  0.666667             640     25   
1        0.465116  0.962264       0.890719  0.850746              73     81   

   new_slide_prediction  
0                  True  
1                  True

In [12]:
segmentation_result 

jaccard_letter   jaccard  letter_dissim  word_dis  frame_token_ct  index  \
0         0.243902  0.932203       0.720313  0.666667             640     25   
1         0.465116  0.962264       0.890719  0.850746              73     81   
2         0.371429  0.911765       0.174129  0.200000             201    144   
3         0.344828  0.884615       0.798030  0.758621              41    155   
4         0.590909  1.000000       0.488889  0.285714              45    163   
5         0.925000  1.000000       0.982906  0.952381             234    188   
6         0.256410  0.967742       0.732836  0.791667             670    203   
7         0.405405  0.927273       0.790698  0.723077             135    324   
8         0.382353  0.900000       0.808847  0.804878             633    333   
9         0.090909  0.904255       0.272300  0.353659             465    442   
10        0.200000  0.928571       0.309064  0.353659             673    493   
11        0.488889  0.945205       0.778237  0.768293             161    559   

    new_slide_prediction  
0                   True  
1                   True  
2                   True  
3                   True  
4                   True  
5                   True  
6                   True  
7                   True  
8                   True  
9                   True  
10                  True  
11                  True